base_image: dgx_aofei:latest

compute_node: A100

num_gpu: 4

job_name: reg_token_with_Quantization_full_pipeline

command:
- export REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/gehealthcarerootca1.crt
- source /qumulo/shared_data/aofei_summer/miniconda3/bin/activate base
- cd /qumulo/shared_data/aofei_summer/RegTok/source
- bash ./scripts/train_vq_full.sh


output_log_path: /qumulo/shared_data/aofei_summer/RegTok/source/logs/stage1_quant-full-pipeline/