base_image: dgx_aofei:latest

compute_node: H1001

num_gpu: 4

job_name: reg_token_full_20epoch_wo_quant

command:
- export REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/gehealthcarerootca1.crt
- source /qumulo/shared_data/aofei_summer/miniconda3/bin/activate base
- cd /qumulo/shared_data/aofei_summer/RegTok/source
- bash ./scripts/train_full.sh


output_log_path: /qumulo/shared_data/aofei_summer/RegTok/source/logs/stage0-full-wo-quant/