num_queries: 20
codebook_size: 0
codebook_embed_dim: 0
num_stages: 3
num_stacks: 1
codebook_l2_norm: True
codebook_show_usage: True
commit_loss_beta: 1.0
entropy_loss_ratio: 0.0

dropout_p: 0.0
use_quantization: False
kmeans: False
num_classes: 17
infer_interpolate: False
finetune_codebook_only: False
use_self_attn: False
upsample_mode: "conv"
pretrained_weights: "/qumulo/shared_data/aofei_summer/CLIPs/unimed_clip_vit_l14.pt"